{% set name = "venv-kernel" %}
{% set version = "1.0.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8aa0b63ac4dab2a967ae7c00ff6f91b9cfb67550c76408714aec52dcf81b5f11

build:
  number: 0
  noarch: python
  entry_points:
    - venv-kernel = venv_kernel.kernel_tool:app
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - ipykernel >=5.5,<7
    - python >=3.6,<4.0
    - rich >=10.7
    - typer >=0.3.2

test:
  imports:
    - venv_kernel
  commands:
    - pip check
    - venv-kernel --help
  requires:
    - pip

about:
  home: https://github.com/bjoseru/venv-kernel
  summary: Create a custom jupyter kernel for your venv.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
