{% set name = "venv-kernel" %}
{% set version = "1.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/venv-kernel-{{ version }}.tar.gz
  sha256: 96d74fc60d0b93baad2562c82a1a68bac8090ce3034520f53dd50e4bc5746542

build:
  number: 0
  noarch: python
  entry_points:
    - venv-kernel = venv_kernel.kernel_tool:app
  script:
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - ipykernel >=5.5,<7
    - python >=3.6
    - rich >=10.7,<11.0
    - typer >=0.3.2,<0.4.0

test:
  imports:
    - venv_kernel
  commands:
    - pip check
    - venv-kernel --help
  requires:
    - pip

about:
  home: https://github.com/bjoseru/venv-kernel
  summary: Create a custom jupyter kernel for your venv.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
