{% set name = "venv-kernel" %}
{% set version = "1.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 926496ca024eae76d38d5491dd6210281b5365fb698b5f22d91449a131d7c842

build:
  number: 0
  noarch: python
  entry_points:
    - venv-kernel = venv_kernel.kernel_tool:app
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - ipykernel >=5.5,<7
    - python >=3.6
    - rich >=10.7,<11.0
    - typer >=0.3.2,<0.4.0

test:
  imports:
    - venv_kernel
  commands:
    - pip check
    - venv-kernel --help
  requires:
    - pip

about:
  home: https://github.com/bjoseru/venv-kernel
  summary: Create a custom jupyter kernel for your venv.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
